trace:
  endpoint: http://127.0.0.1:14268/api/traces
server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: pgx
    source: host=10.7.14.40 user=kmsuser password=4EzUPLVb84Q01YU1RTThW0tqSC8mAU dbname=pay_demo port=7432 TimeZone=Asia/Shanghai
  redis:
    addr: 10.7.14.40:6379
    dial_timeout: 1s
    read_timeout: 0.4s
    write_timeout: 0.6s