// Code generated by ent, DO NOT EDIT.

package refund

import (
	"time"
)

const (
	// Label holds the string label denoting the refund type in the database.
	Label = "refund"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOrderNo holds the string denoting the order_no field in the database.
	FieldOrderNo = "order_no"
	// FieldRefundNo holds the string denoting the refund_no field in the database.
	FieldRefundNo = "refund_no"
	// FieldRefundID holds the string denoting the refund_id field in the database.
	FieldRefundID = "refund_id"
	// FieldTotalFee holds the string denoting the total_fee field in the database.
	FieldTotalFee = "total_fee"
	// FieldRefund holds the string denoting the refund field in the database.
	FieldRefund = "refund"
	// FieldReason holds the string denoting the reason field in the database.
	FieldReason = "reason"
	// FieldRefundStatus holds the string denoting the refund_status field in the database.
	FieldRefundStatus = "refund_status"
	// FieldContentReturn holds the string denoting the content_return field in the database.
	FieldContentReturn = "content_return"
	// FieldContentNotify holds the string denoting the content_notify field in the database.
	FieldContentNotify = "content_notify"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the refund in the database.
	Table = "refunds"
)

// Columns holds all SQL columns for refund fields.
var Columns = []string{
	FieldID,
	FieldOrderNo,
	FieldRefundNo,
	FieldRefundID,
	FieldTotalFee,
	FieldRefund,
	FieldReason,
	FieldRefundStatus,
	FieldContentReturn,
	FieldContentNotify,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
)
